name: service

on:
  push:
    branches: [main]
    paths:
      - service/**
      - .github/workflows/service.yml
  pull_request:
    branches: [main]
    paths:
      - service/**
      - .github/workflows/service.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./service
      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ./service
